import type { DatePickerTokens } from './DatePicker.types';

export const defaultDatePickerTokens: DatePickerTokens = {
  backgroundColor: '#ffffff',
  borderColor: '#e5e7eb',
  borderRadius: '12px',
  padding: '16px',
  fontSize: '14px',
  fontFamily: '"DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  textColor: '#1f2937',
  primaryColor: '#6366f1',
  primaryColorLight: '#e0e7ff',
  secondaryColor: '#f3f4f6',
  hoverColor: '#f9fafb',
  selectedColor: '#6366f1',
  selectedTextColor: '#ffffff',
  disabledColor: '#9ca3af',
  disabledBackgroundColor: '#f3f4f6',
  shadowColor: '0 10px 25px rgba(0, 0, 0, 0.1)',
  sidebarBackgroundColor: '#f8fafc',
  sidebarBorderColor: '#e5e7eb',
  sidebarItemHoverColor: '#f1f5f9',
  sidebarSelectedColor: '#6366f1',
  sidebarSelectedTextColor: '#ffffff',
  calendarHeaderColor: '#374151',
  weekdayColor: '#6b7280',
  rangeBackgroundColor: '#e0e7ff',
  rangeHoverColor: '#c7d2fe',
  todayBorderColor: '#6366f1',
  otherMonthColor: '#d1d5db',
  timeSelectBackgroundColor: '#ffffff',
  timeSelectBorderColor: '#d1d5db',
  iconColor: '#6b7280',
  iconSize: '16px',
  iconSpacing: '8px',
}; 