import type { DropdownTokens } from './Dropdown.types';

export const defaultDropdownTokens: DropdownTokens = {
  backgroundColor: '#ffffff',
  borderColor: '#e5e7eb',
  borderRadius: '8px',
  padding: '12px 16px',
  fontSize: '14px',
  fontFamily: '"DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  textColor: '#1f2937',
  primaryColor: '#6366f1',
  primaryColorLight: '#e0e7ff',
  secondaryColor: '#f3f4f6',
  hoverColor: '#f9fafb',
  selectedColor: '#6366f1',
  selectedTextColor: '#ffffff',
  disabledColor: '#9ca3af',
  disabledBackgroundColor: '#f3f4f6',
  shadowColor: '0 4px 12px rgba(0, 0, 0, 0.1)',
  placeholderColor: '#9ca3af',
  optionPadding: '10px 16px',
  optionHoverColor: '#f1f5f9',
  checkboxColor: '#d1d5db',
  checkboxCheckedColor: '#6366f1',
  dividerColor: '#e5e7eb',
  searchBackgroundColor: '#ffffff',
  searchBorderColor: '#d1d5db',
  loadingColor: '#6366f1',
  errorColor: '#ef4444',
  errorBackgroundColor: '#fef2f2',
  maxHeight: '300px',
  iconColor: '#6b7280',
  iconSize: '16px',
  iconSpacing: '8px',
}; 